import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

interface PDFData {
  name: string;
  dateRange: string;
  rows: any[];
  subtotal: number;
  hst: number;
  total: number;
}

export const generatePDF = (data: PDFData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Branding & Header
  doc.setFontSize(20);
  doc.setTextColor(26, 74, 46); // Deep Green
  doc.text("Ahmadiyya Muslim Jama'at Canada", pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(14);
  doc.setTextColor(184, 134, 11); // Gold
  doc.text("Waqfeen Nazarat - Expense Report", pageWidth / 2, 30, { align: 'center' });

  // User Info Block
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 35, pageWidth - 20, 35);
  
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(`Missionary Name: ${data.name || 'N/A'}`, 20, 45);
  doc.text(`Reporting Period: ${data.dateRange || 'N/A'}`, 20, 52);
  doc.text(`Date Generated: ${new Date().toLocaleDateString()}`, pageWidth - 20, 45, { align: 'right' });

  // Table
  const tableRows = data.rows.map(r => [
    r.date,
    r.description,
    r.category,
    `$${parseFloat(r.amount).toFixed(2)}`,
    r.hasTax ? 'Yes' : 'No'
  ]);

  (doc as any).autoTable({
    startY: 60,
    head: [['Date', 'Description', 'Category', 'Amount (CAD)', 'Tax (13%)']],
    body: tableRows,
    theme: 'grid',
    headStyles: { fillColor: [26, 74, 46], textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [245, 245, 245] },
  });

  // Totals Section
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(`Subtotal: $${data.subtotal.toFixed(2)}`, pageWidth - 20, finalY, { align: 'right' });
  doc.text(`HST (13%): $${data.hst.toFixed(2)}`, pageWidth - 20, finalY + 7, { align: 'right' });
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.text(`Total Amount: $${data.total.toFixed(2)}`, pageWidth - 20, finalY + 15, { align: 'right' });

  // Footer
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Murrabi Expense Tool • Standalone Edition", pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

  doc.save(`Expense_Report_${data.name.replace(/\s+/g, '_')}_${data.dateRange.replace(/\s+/g, '_')}.pdf`);
};
